version: '3.8'

services:
  db:
    image: postgres:16
    container_name: hotel_booking_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hotel_booking
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: hotel_booking_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/hotel_booking
    depends_on:
      - db
    volumes:
      - .:/app  # Для hot-reload

volumes:
  postgres-data: